/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PL.GUI;

import BUS.Utils.Auth;
import BUS.Utils.MsgBox;
import DAL.Entities.NhanVien;
import DAL.Services.NhanVienServices;
import javax.swing.JOptionPane;

/**
 *
 * @author Cu Gau
 */
public class DoiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form ĐoiMatKhau
     */
    public DoiMatKhau() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        init();
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
            dispose();
        }
        txttendangnhap.setText(Auth.user.getMaNhanVien());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttendangnhap = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtmatkhauhientai = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtxacnhanmatkhau = new javax.swing.JPasswordField();
        txtmatkhaumoi = new javax.swing.JPasswordField();
        btnxacnhan = new javax.swing.JButton();
        btnhuybo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ĐỔI MẬT KHẨU");

        jPanel1.setBackground(new java.awt.Color(136, 116, 163));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(228, 220, 241));
        jLabel2.setText("Tên Đăng Nhập:");

        txttendangnhap.setBackground(new java.awt.Color(228, 220, 241));
        txttendangnhap.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(228, 220, 241));
        jLabel1.setText("Mật Khẩu Hiện Tại:");

        txtmatkhauhientai.setBackground(new java.awt.Color(228, 220, 241));
        txtmatkhauhientai.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(228, 220, 241));
        jLabel3.setText("Mật Khẩu Mới:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(228, 220, 241));
        jLabel4.setText("Xác nhận Mật Khẩu Mới:");

        txtxacnhanmatkhau.setBackground(new java.awt.Color(228, 220, 241));
        txtxacnhanmatkhau.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        txtmatkhaumoi.setBackground(new java.awt.Color(228, 220, 241));
        txtmatkhaumoi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        btnxacnhan.setBackground(new java.awt.Color(136, 116, 163));
        btnxacnhan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnxacnhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PL/Icon/Handshake.png"))); // NOI18N
        btnxacnhan.setText("Xác Nhận");
        btnxacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxacnhanActionPerformed(evt);
            }
        });

        btnhuybo.setBackground(new java.awt.Color(136, 116, 163));
        btnhuybo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnhuybo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PL/Icon/close.png"))); // NOI18N
        btnhuybo.setText("Hủy Bỏ");
        btnhuybo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuyboActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(61, 35, 82));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(228, 220, 241));
        jLabel5.setText("Đổi Mật Khẩu");
        jPanel2.add(jLabel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnxacnhan)
                        .addGap(18, 18, 18)
                        .addComponent(btnhuybo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(39, 39, 39))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtxacnhanmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmatkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmatkhauhientai, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnhuybo, btnxacnhan});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmatkhauhientai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmatkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtxacnhanmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxacnhan)
                    .addComponent(btnhuybo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnxacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxacnhanActionPerformed
        if (Auth.user.getMaNhanVien().equalsIgnoreCase(txttendangnhap.getText())) {
            if (check()) {
                doimatkhau();
            }
        } else {
            MsgBox.alert(this, "Bạn chỉ được đổi mật khẩu của tài khoản hiện đang đăng nhập!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnxacnhanActionPerformed

    private void btnhuyboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuyboActionPerformed
        huybo();        // TODO add your handling code here:
    }//GEN-LAST:event_btnhuyboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhuybo;
    private javax.swing.JButton btnxacnhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtmatkhauhientai;
    private javax.swing.JPasswordField txtmatkhaumoi;
    private javax.swing.JTextField txttendangnhap;
    private javax.swing.JPasswordField txtxacnhanmatkhau;
    // End of variables declaration//GEN-END:variables

    void init() {
        setLocationRelativeTo(null);
    }
    NhanVienServices daonv = new NhanVienServices();

    void doimatkhau() {

        String manv = txttendangnhap.getText();
        String matkhau = new String(txtmatkhauhientai.getPassword());
        String matkhaumoi = new String(txtmatkhaumoi.getPassword());
        String XNmatkhaumoi = new String(txtxacnhanmatkhau.getPassword());
        NhanVien nv = daonv.getListNhanVienByID(manv);
        if (nv == null) {
            JOptionPane.showMessageDialog(this, "sai tên đăng nhập");
            txttendangnhap.requestFocus();
        } else if (!matkhau.equals(nv.getMaKhau())) {
            JOptionPane.showMessageDialog(this, "sai mật khẩu");
            txtmatkhauhientai.requestFocus();
        } else if (!matkhaumoi.equals(XNmatkhaumoi)) {
            JOptionPane.showMessageDialog(this, "xác nhận mật khẩu không đúng");
        } else {
            nv.setMaKhau(matkhaumoi);
            daonv.updateNhanVien(nv);
            JOptionPane.showMessageDialog(this, "đổi mật khẩu thành công");
            this.dispose();
        }
    }

    void huybo() {
        this.dispose();
    }

    boolean check() {
        String pass = new String(txtmatkhauhientai.getPassword());
        String pass1 = new String(txtmatkhaumoi.getPassword());
        String pass2 = new String(txtxacnhanmatkhau.getPassword());
        String tenDN = txttendangnhap.getText();
        if (tenDN.isEmpty()) {
            JOptionPane.showMessageDialog(this, "chưa nhập tên đăng nhập");
            txttendangnhap.requestFocus();
            return false;
        } else if (pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "chưa nhập mật khẩu");
            txtmatkhauhientai.requestFocus();
            return false;
        } else if (pass1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "chưa nhập mật khẩu mới");
            txtmatkhaumoi.requestFocus();
            return false;
        } else if (pass2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "chưa xác nhận mật khẩu mới");
            txtxacnhanmatkhau.requestFocus();
            return false;
        }
        return true;
    }
}
