/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PL.GUI;

import BUS.Utils.MsgBox;
import DAL.Entities.ChiTietDichVu;
import DAL.Entities.ChiTietHoaDon;
import DAL.IServices.IChiTietDichVuServices;
import DAL.IServices.IChiTietHoaDonServices;
import DAL.Services.ChiTietDichVuServices;
import DAL.Services.ChiTietHoaDonServices;

/**
 *
 * @author PC
 */
public final class Frm_GoiDichVu extends javax.swing.JDialog {

    String maPhong_CT, maDichVu_CT, tenDichVu_CT, tenLoaiDichVu_CT, maHDCT_CT, maCTDV_CT;
    Frm_HoaDon hoaDon;
    int Them_Sua_CT;/*Thêm: 1 - Sửa: 2*/
    int soLuong_CT;
    IChiTietHoaDonServices _iChiTietHoaDon = new ChiTietHoaDonServices();
    IChiTietDichVuServices _iChiTietDichVu = new ChiTietDichVuServices();

    public Frm_GoiDichVu(java.awt.Frame parent, boolean modal, String maPhong, String maDichVu, String tenDichVu, String maHDCT, int Them_Sua, String maCTDV, int soLuong) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        maPhong_CT = maPhong;
        maDichVu_CT = maDichVu;
        tenDichVu_CT = tenDichVu;
        maHDCT_CT = maHDCT;
        hoaDon = (Frm_HoaDon) parent;
        Them_Sua_CT = Them_Sua;
        maCTDV_CT = maCTDV;
        soLuong_CT = soLuong;
        thongTin();
        if (Them_Sua_CT == 2) {
            btnControl.setText("Update");
        }
    }

    public void thongTin() {
        lblPhong.setText("Phòng " + maPhong_CT);
        lblTenDichVu.setText(tenDichVu_CT);
        if (Them_Sua_CT == 2) {
            txtSoLuong.setText(soLuong_CT + "");
        }
    }

    public void addDichVu() {
        try {
            if (MsgBox.confirm(this, "Bạn có chắc chắn muốn thêm dịch vụ?")) {
                ChiTietHoaDon cthd = _iChiTietHoaDon.getListChiTietHoaDonByMaPhong(maPhong_CT);
                ChiTietDichVu check = _iChiTietDichVu.checkDichVu(maHDCT_CT, maDichVu_CT);
                ChiTietDichVu ctdv = new ChiTietDichVu();
                ctdv.setMaHoaDonChiTiet(cthd.getMaHoaDonChiTiet());
                ctdv.setMaDichVu(maDichVu_CT);
                if (check == null) {
                    ctdv.setMaChiTietDichVu(_iChiTietDichVu.getMaCTDVAuto());
                    ctdv.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
                    _iChiTietDichVu.addChiTietDichVu(ctdv);
                } else {
                    ctdv.setMaChiTietDichVu(check.getMaChiTietDichVu());
                    ctdv.setSoLuong(check.getSoLuong() + Integer.parseInt(txtSoLuong.getText()));
                    _iChiTietDichVu.updateChiTietDichVu(ctdv);
                }

                MsgBox.alert(this, "Thêm dịch vụ thành công!");
                hoaDon.fillToDichVuPhong();
                this.dispose();
            }
        } catch (Exception e) {
        }
    }

    public void updateDichVu() {
        try {
            if (MsgBox.confirm(this, "Bạn có chắc chắn muốn sửa số lượng của dịch vụ?")) {
                ChiTietDichVu ctdv = new ChiTietDichVu();
                ctdv.setMaChiTietDichVu(maCTDV_CT);
                ctdv.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
                _iChiTietDichVu.updateSoLuong(ctdv);

                MsgBox.alert(this, "Sửa số lượng của dịch vụ thành công!");
                hoaDon.fillToDichVuPhong();
                this.dispose();
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPhong = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTru = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        btnCong = new javax.swing.JButton();
        lblTenDichVu = new javax.swing.JLabel();
        btnControl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DỊCH VỤ");

        jPanel1.setBackground(new java.awt.Color(61, 35, 82));

        lblPhong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPhong.setForeground(new java.awt.Color(228, 220, 241));
        lblPhong.setText("Phòng");
        jPanel1.add(lblPhong);

        jPanel2.setBackground(new java.awt.Color(136, 116, 163));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(228, 220, 241));
        jLabel1.setText("Tên Dịch Vụ:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(228, 220, 241));
        jLabel5.setText("Số Lượng:");

        btnTru.setBackground(new java.awt.Color(136, 116, 163));
        btnTru.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnTru.setText("-");
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });

        txtSoLuong.setBackground(new java.awt.Color(228, 220, 241));
        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtSoLuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSoLuong.setText("1");

        btnCong.setBackground(new java.awt.Color(136, 116, 163));
        btnCong.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCong.setText("+");
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });

        lblTenDichVu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTenDichVu.setForeground(new java.awt.Color(228, 220, 241));
        lblTenDichVu.setText("Hoho");

        btnControl.setBackground(new java.awt.Color(136, 116, 163));
        btnControl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnControl.setText("Add");
        btnControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTenDichVu))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(btnTru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCong)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnControl)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTenDichVu))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTru)
                    .addComponent(btnCong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnControl)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        try {
            int soLuong = Integer.parseInt(txtSoLuong.getText());
            soLuong++;
            txtSoLuong.setText(soLuong + "");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        try {
            int soLuong = Integer.parseInt(txtSoLuong.getText());
            if (soLuong > 1) {
                soLuong--;
                txtSoLuong.setText(soLuong + "");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnTruActionPerformed

    private void btnControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlActionPerformed
        if (Them_Sua_CT == 1) {
            addDichVu();
        } else {
            updateDichVu();
        }
    }//GEN-LAST:event_btnControlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_GoiDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_GoiDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_GoiDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_GoiDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_GoiDichVu dialog = new Frm_GoiDichVu(new javax.swing.JFrame(), true, "", "", "", "", 0, "", 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnControl;
    private javax.swing.JButton btnTru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblTenDichVu;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
