package PL.GUI;

import BUS.IServices.IQLLoaiDichVuServices;
import BUS.Services.QLLoaiDichVuServices;
import BUS.Utils.MsgBox;
import DAL.Entities.LoaiDichVu;
import DAL.Services.LoaiDichVuServices;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Frm_LoaiDichVu extends javax.swing.JFrame {

    IQLLoaiDichVuServices _iLoaiDV = new QLLoaiDichVuServices();
    LoaiDichVuServices ldv = new LoaiDichVuServices();
    int _index = 0;
    ImageIcon iconTick = new ImageIcon("src\\PL\\Icon\\Tick.png");
    ImageIcon iconTrash = new ImageIcon("src\\PL\\Icon\\Trash.png");
    ImageIcon iconError = new ImageIcon("src\\PL\\Icon\\Problem.png");

    public Frm_LoaiDichVu() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tbnloaidichvu.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
//        tbnloaidichvu.getTableHeader().setBackground(new Color(34, 47, 62));
//        tbnloaidichvu.getTableHeader().setForeground(new Color(255, 255, 255));
        filltoTable();
        showForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtmaloaidv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttendv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtghichu = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbnloaidichvu = new javax.swing.JTable();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOẠI DỊCH VỤ");

        jPanel1.setBackground(new java.awt.Color(10, 189, 227));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã loại dịch vụ");

        txtmaloaidv.setEditable(false);
        txtmaloaidv.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtmaloaidv.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên loại dịch vụ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ghi chú");

        txttendv.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txttendv.setBorder(null);

        txtghichu.setColumns(20);
        txtghichu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtghichu.setLineWrap(true);
        txtghichu.setRows(5);
        txtghichu.setBorder(null);
        jScrollPane1.setViewportView(txtghichu);

        tbnloaidichvu.setAutoCreateRowSorter(true);
        tbnloaidichvu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại dịch vụ", "Tên loại dịch vụ", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbnloaidichvu.setGridColor(new java.awt.Color(255, 255, 255));
        tbnloaidichvu.getTableHeader().setReorderingAllowed(false);
        tbnloaidichvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbnloaidichvuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbnloaidichvu);

        btnthem.setBackground(new java.awt.Color(34, 47, 62));
        btnthem.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnthem.setForeground(new java.awt.Color(255, 255, 255));
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setBackground(new java.awt.Color(34, 47, 62));
        btnsua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnsua.setForeground(new java.awt.Color(255, 255, 255));
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setBackground(new java.awt.Color(34, 47, 62));
        btnxoa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnxoa.setForeground(new java.awt.Color(255, 255, 255));
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(34, 47, 62));
        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("Làm mới");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(10, 189, 227));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quản Lý Loại Dịch Vụ");
        jPanel2.add(jLabel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txttendv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                    .addComponent(txtmaloaidv, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnthem)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnsua))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnxoa)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnclear))))
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnclear, btnsua, btnthem, btnxoa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmaloaidv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addComponent(txttendv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnthem)
                            .addComponent(btnsua))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnxoa)
                            .addComponent(btnclear)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        clear();
    }//GEN-LAST:event_btnclearActionPerformed

    private void tbnloaidichvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnloaidichvuMouseClicked
        try {
            _index = tbnloaidichvu.getSelectedRow();
            showForm();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbnloaidichvuMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        try {
            if (checkAddAll() == false) {
                return;
            } else {
                int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm loại dịch vụ ?");
                if (choice != JOptionPane.YES_OPTION) {
                    return;
                }
                _iLoaiDV.add(txtmaloaidv, txttendv, txtghichu);
                _iLoaiDV.fillToTable(tbnloaidichvu);
                JOptionPane.showMessageDialog(this, "Thêm loại dịch vụ thành công !", "Thông báo", 0, iconTick);
                clear();
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Không thể thêm mới!");
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        try {
            if (checkEditAll() == false) {
                return;
            } else {
                int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn cập nhật loại dịch vụ ?");
                if (choice != JOptionPane.YES_OPTION) {
                    return;
                }
                _iLoaiDV.edit(txtmaloaidv, txttendv, txtghichu);
                _iLoaiDV.fillToTable(tbnloaidichvu);
                JOptionPane.showMessageDialog(this, "Cập nhật loại dịch vụ thành công !", "Thông báo", 0, iconTick);
                clear();
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Không thể sửa!");
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        try {
            int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa loại dịch vụ ?");
            if (choice != JOptionPane.YES_OPTION) {
                return;
            }
            _iLoaiDV.delete(txtmaloaidv);
            _iLoaiDV.fillToTable(tbnloaidichvu);
            JOptionPane.showMessageDialog(this, "Xóa loại dịch vụ thành công !", "Thông báo", 0, iconTrash);
            clear();
        } catch (Exception e) {
            MsgBox.alert(this, "Không thể xóa!");
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Frm_LoaiDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Frm_LoaiDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Frm_LoaiDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Frm_LoaiDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_LoaiDichVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbnloaidichvu;
    private javax.swing.JTextArea txtghichu;
    private javax.swing.JTextField txtmaloaidv;
    private javax.swing.JTextField txttendv;
    // End of variables declaration//GEN-END:variables

    private void filltoTable() {
        _iLoaiDV.fillToTable(tbnloaidichvu);
    }

    private void showForm() {
        txtmaloaidv.setText(tbnloaidichvu.getValueAt(_index, 0).toString());
        txttendv.setText(tbnloaidichvu.getValueAt(_index, 1).toString());
        txtghichu.setText(tbnloaidichvu.getValueAt(_index, 2).toString());
    }

    private void clear() {
        txtghichu.setText("");
        txtmaloaidv.setText("");
        txttendv.setText("");
        txtmaloaidv.setEditable(true);
    }

    private boolean checkAddAll() {
        String madv = txtmaloaidv.getText();
        String tendv = txttendv.getText();
        String ghichu = txtghichu.getText();
        if (madv.length() == 0 || tendv.length() == 0 || ghichu.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không được để trống dữ liệu !", "Thông báo", 0, iconError);
            return false;
        }
        if (ldv.getListLoaiDichVuByID(madv) != null) {
            JOptionPane.showMessageDialog(this, "Mã loại dịch vụ đã tồn tại !", "Thông báo", 0, iconError);
            return false;
        }
        return true;
    }

    private boolean checkEditAll() {
        String madv = txtmaloaidv.getText();
        String tendv = txttendv.getText();
        String ghichu = txtghichu.getText();
        if (madv.length() == 0 || tendv.length() == 0 || ghichu.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không được để trống dữ liệu !", "Thông báo", 0, iconError);
            return false;
        }
        return true;
    }
}
