/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PL.GUI;

import BUS.Utils.MsgBox;
import BUS.Utils.XDate;
import BUS.Utils.XValidated;
import DAL.Entities.ChiTietHoaDon;
import DAL.Entities.LoaiHinhThue;
import DAL.IServices.IChiTietHoaDonServices;
import DAL.IServices.ILoaiHinhThueServices;
import DAL.Services.ChiTietHoaDonServices;
import DAL.Services.LoaiHinhThueServices;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author PC
 */
public final class Frm_UpdateHDCT extends javax.swing.JDialog {

    private Frm_HoaDon hoaDon;
    public String maHDCT_Update;
    IChiTietHoaDonServices _iChiTietHoaDon = new ChiTietHoaDonServices();
    ILoaiHinhThueServices _iLoaiHinhThue = new LoaiHinhThueServices();
    DefaultComboBoxModel model;

    public Frm_UpdateHDCT(java.awt.Frame parent, boolean modal, String maHDCT) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        hoaDon = (Frm_HoaDon) parent;
        model = (DefaultComboBoxModel) cboLoaiHinhThue.getModel();
        fillLoaiHinhThue();
        maHDCT_Update = maHDCT;
        layThongTin();
    }

    public void layThongTin() {
        try {
            ChiTietHoaDon cthd = _iChiTietHoaDon.getListChiTietHoaDonByID(maHDCT_Update);
            lblMaHDCT.setText(cthd.getMaHoaDonChiTiet());
            List<LoaiHinhThue> list = _iLoaiHinhThue.getListLoaiHinhThue();
            int i = 0;
            for (LoaiHinhThue lht : list) {
                if (cthd.getMaLoaiHinhThue().equals(lht.getMaLoaiHinhThue())) {
                    break;
                }
                i++;
            }
            lblPhong.setText("Phòng " + cthd.getMaPhong());
            cboLoaiHinhThue.setSelectedIndex(i);
            txtNgayThue.setDate(cthd.getNgayThue());
            txtNgayThue.setDateFormatString("dd-MM-yyyy HH:mm:ss");
            txtNgayTraDuKien.setDate(cthd.getNgayDuKienTra());
            txtNgayTraDuKien.setDateFormatString("dd-MM-yyyy HH:mm:ss");
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi này liên hệ zới anh Zũ đẹp zai để được giải quyết!");
            e.printStackTrace();
        }
    }

    public void updateHDCT() {
        try {
            if (!isValidated()) {
                return;
            }
            if (MsgBox.confirm(this, "Bạn có chắc chắn muốn update hóa đơn này?")) {
                ChiTietHoaDon cthd = new ChiTietHoaDon();
                cthd.setMaHoaDonChiTiet(maHDCT_Update);
                LoaiHinhThue lht = (LoaiHinhThue) cboLoaiHinhThue.getSelectedItem();
                cthd.setMaLoaiHinhThue(lht.getMaLoaiHinhThue());
                cthd.setNgayThue(txtNgayThue.getDate());
                cthd.setNgayDuKienTra(txtNgayTraDuKien.getDate());
                _iChiTietHoaDon.updateChiTietHoaDon_Version1(cthd);
                MsgBox.alert(this, "Update thành công!");
                hoaDon.fillThongTin();
                this.dispose();
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi này liên hệ zới anh Zũ đẹp zai để được giải quyết!");
            e.printStackTrace();
        }
    }

    public void fillLoaiHinhThue() {
        try {
            model.removeAllElements();
            List<LoaiHinhThue> list = _iLoaiHinhThue.getListLoaiHinhThue();
            for (LoaiHinhThue lht : list) {
                model.addElement(lht);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi này liên hệ zới anh Zũ đẹp zai để được giải quyết!");
            e.printStackTrace();
        }
    }

    public boolean isValidated() {
        try {
            Date ngayChek = txtNgayTraDuKien.getDate();
            String ngayCheckString = XDate.toString(ngayChek, "dd-MM-yyyy HH:mm:ss");
        } catch (Exception e) {
            MsgBox.alert(this, "Vui lòng chọn ngày dự kiến trả phòng!");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPhong = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblMaHDCT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNgayTraDuKien = new com.toedter.calendar.JDateChooser();
        txtNgayThue = new com.toedter.calendar.JDateChooser();
        cboLoaiHinhThue = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HÓA ĐƠN");
        setBackground(new java.awt.Color(136, 116, 163));

        jPanel1.setBackground(new java.awt.Color(61, 35, 82));

        lblPhong.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPhong.setForeground(new java.awt.Color(228, 220, 241));
        lblPhong.setText("Phòng");
        jPanel1.add(lblPhong);

        jPanel2.setBackground(new java.awt.Color(136, 116, 163));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(228, 220, 241));
        jLabel2.setText("Mã HDCT:");

        lblMaHDCT.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMaHDCT.setForeground(new java.awt.Color(228, 220, 241));
        lblMaHDCT.setText("HDCT01");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(228, 220, 241));
        jLabel6.setText("Loại Hình Thuê:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(228, 220, 241));
        jLabel9.setText("Bắt Đầu Thuê:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(228, 220, 241));
        jLabel8.setText("Dự Kiến Trả:");

        txtNgayTraDuKien.setBackground(new java.awt.Color(228, 220, 241));
        txtNgayTraDuKien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        txtNgayThue.setBackground(new java.awt.Color(228, 220, 241));
        txtNgayThue.setEnabled(false);
        txtNgayThue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        cboLoaiHinhThue.setBackground(new java.awt.Color(228, 220, 241));
        cboLoaiHinhThue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        btnUpdate.setBackground(new java.awt.Color(136, 116, 163));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdate))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblMaHDCT)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayTraDuKien, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(cboLoaiHinhThue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNgayThue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblMaHDCT))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboLoaiHinhThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txtNgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(txtNgayTraDuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboLoaiHinhThue, txtNgayThue, txtNgayTraDuKien});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateHDCT();
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_UpdateHDCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_UpdateHDCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_UpdateHDCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_UpdateHDCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_UpdateHDCT dialog = new Frm_UpdateHDCT(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboLoaiHinhThue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMaHDCT;
    private javax.swing.JLabel lblPhong;
    private com.toedter.calendar.JDateChooser txtNgayThue;
    private com.toedter.calendar.JDateChooser txtNgayTraDuKien;
    // End of variables declaration//GEN-END:variables
}
