package PL.GUI;

import BUS.IServices.IQLTangServices;
import BUS.Services.QLTangServices;
import BUS.Utils.MsgBox;
import DAL.Services.TangServices;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Frm_Tang extends javax.swing.JFrame {

    IQLTangServices _iTang = new QLTangServices();
    TangServices tang = new TangServices();
    int _index = 0;
    ImageIcon iconTick = new ImageIcon("src\\PL\\Icon\\Tick.png");
    ImageIcon iconTrash = new ImageIcon("src\\PL\\Icon\\Trash.png");
    ImageIcon iconError = new ImageIcon("src\\PL\\Icon\\Problem.png");

    public Frm_Tang() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tbltang.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        filltoTable();
        showForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtmatang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtsotang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltang = new javax.swing.JTable();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnlammoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ TẦNG ");

        jPanel1.setBackground(new java.awt.Color(10, 189, 227));

        txtmatang.setEditable(false);
        txtmatang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtmatang.setBorder(null);
        txtmatang.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mã tầng");

        txtsotang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtsotang.setBorder(null);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Số tầng");

        tbltang.setAutoCreateRowSorter(true);
        tbltang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tbltang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tầng", "Số tầng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbltang.setGridColor(new java.awt.Color(255, 255, 255));
        tbltang.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tbltang.setRowHeight(24);
        tbltang.setSelectionBackground(new java.awt.Color(10, 189, 227));
        tbltang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbltang);

        btnthem.setBackground(new java.awt.Color(34, 47, 62));
        btnthem.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnthem.setForeground(new java.awt.Color(255, 255, 255));
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setBackground(new java.awt.Color(34, 47, 62));
        btnsua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnsua.setForeground(new java.awt.Color(255, 255, 255));
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setBackground(new java.awt.Color(34, 47, 62));
        btnxoa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnxoa.setForeground(new java.awt.Color(255, 255, 255));
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnlammoi.setBackground(new java.awt.Color(34, 47, 62));
        btnlammoi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnlammoi.setForeground(new java.awt.Color(255, 255, 255));
        btnlammoi.setText("Làm mới");
        btnlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlammoiActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(10, 189, 227));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quản Lý Tầng");
        jPanel2.add(jLabel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnxoa)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnlammoi))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnthem)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnsua)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(txtsotang, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                .addComponent(txtmatang)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnlammoi, btnsua, btnthem, btnxoa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtmatang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtsotang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnthem)
                            .addComponent(btnsua))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnxoa)
                            .addComponent(btnlammoi))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbltangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltangMouseClicked
        try {
            _index = tbltang.getSelectedRow();
            showForm();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbltangMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        try {
            if (checkAddAll() == false) {
                return;
            } else {
                int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm tầng ?");
                if (choice != JOptionPane.YES_OPTION) {
                    return;
                }
                _iTang.add(txtmatang, txtsotang);
                _iTang.fillToTable(tbltang);
                JOptionPane.showMessageDialog(this, "Thêm tầng thành công !", "Thông báo", 0, iconTick);
                clear();
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Không thể thêm mới!");
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        try {
            if (checkEditAll() == false) {
                return;
            } else {
                int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn cập nhật loại dịch vụ ?");
                if (choice != JOptionPane.YES_OPTION) {
                    return;
                }
                _iTang.edit(txtmatang, txtsotang);
                _iTang.fillToTable(tbltang);
                JOptionPane.showMessageDialog(this, "Cập nhật loại dịch vụ thành công !", "Thông báo", 0, iconTick);
                clear();
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Không thể sửa!");
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        try {
            int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa tầng ?");
            if (choice != JOptionPane.YES_OPTION) {
                return;
            }
            _iTang.delete(txtmatang);
            _iTang.fillToTable(tbltang);
            JOptionPane.showMessageDialog(this, "Xóa tầng thành công !", "Thông báo", 0, iconTrash);
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tầng đang được sử dụng !", "Thông báo", 0, iconError);
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlammoiActionPerformed
        clear();
    }//GEN-LAST:event_btnlammoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Frm_Tang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Frm_Tang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Frm_Tang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Frm_Tang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Tang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlammoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbltang;
    private javax.swing.JTextField txtmatang;
    private javax.swing.JTextField txtsotang;
    // End of variables declaration//GEN-END:variables

    private void filltoTable() {
        _iTang.fillToTable(tbltang);
    }

    private void showForm() {
        txtmatang.setText(tbltang.getValueAt(_index, 0).toString());
        txtsotang.setText(tbltang.getValueAt(_index, 1).toString());
    }

    private boolean checkAddAll() {
        String maTang = txtmatang.getText();
        int soTang;
        if (maTang.length() == 0 || txtsotang.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không được để trống dữ liệu !", "Thông báo", 0, iconError);
            return false;
        }
        try {
            soTang = Integer.parseInt(txtsotang.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số tầng phải là số nguyên !", "Thông báo", 0, iconError);
            return false;
        }
        if (soTang < 0) {
            JOptionPane.showMessageDialog(this, "Số tầng không phù hợp !", "Thông báo", 0, iconError);
            return false;
        }
        if (tang.getListTangByID(maTang) != null) {
            JOptionPane.showMessageDialog(this, "Mã tầng đã tồn tại !", "Thông báo", 0, iconError);
            return false;
        }
        return true;
    }

    private void clear() {
        txtmatang.setText("");
        txtsotang.setText("");
        txtmatang.setEditable(true);
        txtmatang.setEnabled(true);
    }

    private boolean checkEditAll() {
        String maTang = txtmatang.getText();
        int soTang;
        if (maTang.length() == 0 || txtsotang.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không được để trống dữ liệu !", "Thông báo", 0, iconError);
            return false;
        }
        try {
            soTang = Integer.parseInt(txtsotang.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số tầng phải là số nguyên !", "Thông báo", 0, iconError);
            return false;
        }
        if (soTang < 0) {
            JOptionPane.showMessageDialog(this, "Số tầng không phù hợp !", "Thông báo", 0, iconError);
            return false;
        }
        return true;
    }
}
